baseurl = "https://crazyoptimist.net/"
#relativeurls = true
title = "Crazy Optimist"
author = "Crazy Optimist"
copyright = "Copyright @ 2019-2020, Crazy Optimist; all rights reserved."

# canonifyurls = true
paginate = 20
theme = "hugo-clarity"

disqusShortname = "crazy-optimist"

DefaultContentLanguage = "en"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true # change to false to disable inclusion of rawHTML and math functions
      xhtml = false
    [markup.goldmark.extensions]
      typographer = false
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = "--"
    lineNoStart = 1
    lineNos = true # always set to true # else line numbers won't show at all! even when you toggle them on in the UI
    lineNumbersInTable = false # toggling this on (i.e to true) or deleting this line will break the code blocks functionality. Will
    noClasses = false
    style = "monokai"
    tabWidth = 2

[params]
    author = "Crazy Optimist"
    introDescription = "Crazy Optimist, Software Engineer"
    description = "A crazy simple stupid thing separates the doers from the dreamers."
    ga_analytics = ""
    numberOfTagsShown = 14
    fallBackOgImage = ""
    codeMaxLines = 100
    codeLineNumbers = false
    mainSections = ["posts", "about"]
    centerLogo = false
    logo = "logos/logo.png"
    figurePositionShow = false
    figurePositionLabel = "Figure"
    mobileNavigation = "left"
    enforceLightMode = true
    languageMenuName = "Lang"
    titleSeparator = "|"
    numberOfRecentPosts = 2
    numberOfFeaturedPosts = 10

#Menu links
[[menus.main]]
    name = "Blog"
    weight = 1
    url  = "/posts"
[[menus.main]]
    name = "About"
    weight = 2
    url = "/about"
