#baseurl = "https://crazyoptimist.net"
relativeURLs = true
title = "Crazy Optimist"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
    author = "Crazy Optimist"
    info = "Crazy Optimist and Software Engineer"
    description = "A crazy simple stupid thing separates the doers from the dreamers."
    keywords = "crazyoptimist,optimist,optimistic,optimism,crazy"
    avatarurl = "images/avatar.svg"

    favicon_32 = "/favicon-32x32.png"
    favicon_16 = "/favicon-16x16.png"
    touchicon = "/apple-touch-icon.png"

    footercontent = ""

    hidecredits = true
    hidecopyright = false

    rtl = false
    math = false
    custom_css = []
    custom_js = []
    
    colorscheme = "auto"
    enableTwemoji = true
    dateformat = "January 1, 2019"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/CrazyOptimist/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/dockerlead/"
[[params.social]]
    name = "Email"
    icon = "fas fa-envelope-open-text fa-2x"
    weight = 3
    url = "mailto:hey@crazyoptimist.net"
[[params.social]]
    name = "DEV"
    icon = "fab fa-dev fa-2x"
    weight = 4
    url = "https://dev.to/crazyoptimist"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium fa-2x"
    weight = 5
    url = "https://medium.com/@crazyoptimist"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
